/* Generated by RelicListMaker __APP_VERSION__ */
(() => {
    'use strict';

    const MASTER_DATALIST_ID = 'master-relic-options';
    const MASTER_DEMERIT_DATALIST_ID = 'master-demerit-options';
    const DUPLICATE_KEY = 'Duplicate';
    const FAVORITE_KEY = 'Favorite';
    const ITEM_COLOR_OPTIONS = [
        { key: 'red', label: '赤', className: 'item-color-red' },
        { key: 'yellow', label: '黄', className: 'item-color-yellow' },
        { key: 'green', label: '緑', className: 'item-color-green' },
        { key: 'blue', label: '青', className: 'item-color-blue' }
    ];

    const ITEM_RELIC_TYPE_OPTIONS = [
        { key: '', label: '未' },
        { key: 'normal', label: '通常' },
        { key: 'deep', label: '深層' }
    ];

    let syncTagSearchOptions = null;

    const RELIC_TYPE_ALL = 'all';
    const RELIC_TYPE_MERGED = 'merged';
    const RELIC_TYPE_LABELS = {
        [RELIC_TYPE_ALL]: 'すべて',
        normal: '通常',
        deep: '深層'
    };

    const VIEW_BOX_STORAGE_PREFIX = 'gallery.itemImageViewBox';
    const VIEW_BOX_FALLBACK = 'inset(0px 180px 0px 0px)';
    const VIEW_BOX_MAX_LENGTH = 200;
    const VIEW_BOX_INVALID_PATTERN = /['";<>\\{}]/;

    const body = document.body;
    const {
        resultsCsv: initialCsvPath = '',
        imgDir: imageDir = '.',
        labelSymbols: labelSymbolsJson = '[]',
        masterCsv: masterCsvPath = '',
        masterJson: masterJsonPath = '',
        masterOptions: masterOptionsJson = '[]',
        masterOptionsMap: masterOptionsMapJson = '{}',
        masterLevels: masterLevelsJson = '{}',
        masterLevelsMap: masterLevelsMapJson = '{}',
        masterCsvMap: masterCsvMapJson = '{}',
        masterDemeritCsv: masterDemeritCsvPath = '',
        masterDemeritJson: masterDemeritJsonPath = '',
        masterDemeritOptions: masterDemeritOptionsJson = '[]',
        masterDemeritOptionsMap: masterDemeritOptionsMapJson = '{}',
        masterDemeritCsvMap: masterDemeritCsvMapJson = '{}',
        masterDemeritRulesMap: masterDemeritRulesMapJson = '{}',
        datasets: datasetsJson = '[]',
        activeDataset: activeDatasetAttr = ''
    } = body.dataset || {};

    const datasetUtilsFactory = window.galleryDatasetUtilsFactory || null;
    const datasetUtils =
        datasetUtilsFactory && typeof datasetUtilsFactory.createDatasetUtils === 'function'
            ? datasetUtilsFactory.createDatasetUtils()
            : (window.galleryDatasetUtils && typeof window.galleryDatasetUtils === 'object'
                  ? window.galleryDatasetUtils
                  : null);

    if (!datasetUtils) {
        throw new Error('gallery dataset utilities are not available');
    }

    const {
        parseDatasets,
        parseDatasetIndex,
        cloneDatasetSources,
        areSourcesEqual,
        resolveDatasetState
    } = datasetUtils;

    const domUtilsFactory = window.galleryDomUtilsFactory || null;
    const domUtilsInstance =
        (domUtilsFactory && typeof domUtilsFactory.createDomUtils === 'function'
            ? domUtilsFactory.createDomUtils({ document })
            : window.galleryDomUtils) || null;

    if (!domUtilsInstance) {
        throw new Error('gallery dom utilities are not available');
    }

    const {
        setHidden: setElementHidden,
        clearChildren: clearElementChildren,
        updateStatusElement,
        applyInlineStyles: applyInlineStylesToElement,
        ensureElement: ensureDomElement
    } = domUtilsInstance;

    if (
        typeof setElementHidden !== 'function' ||
        typeof clearElementChildren !== 'function' ||
        typeof updateStatusElement !== 'function' ||
        typeof applyInlineStylesToElement !== 'function' ||
        typeof ensureDomElement !== 'function'
    ) {
        throw new Error('gallery dom utilities are incomplete');
    }

    const dataUtils = window.galleryDataUtils || null;

    if (!dataUtils) {
        throw new Error('gallery data utilities are not available');
    }

    const {
        sanitizeLevelList,
        normalizeLevelPlaceholder: normalizeLevelPlaceholderValue,
        normalizeEffectName,
        effectKey,
        normalizeLevelNumericValue,
        sortLevelsAscending,
        parseLevelTokens,
        parseMasterOptions,
        parseMasterLevels,
        normalizeEffectLevelPlaceholders: normalizeEffectLevelPlaceholdersFromUtils,
        normalizeRelicTypeColumns,
        parseTagTokens,
        formatTagTokens,
        serializeTagTokens
    } = dataUtils;

    const dataUtilsMissing = [
        ['sanitizeLevelList', sanitizeLevelList],
        ['normalizeLevelPlaceholder', normalizeLevelPlaceholderValue],
        ['normalizeEffectName', normalizeEffectName],
        ['effectKey', effectKey],
        ['normalizeLevelNumericValue', normalizeLevelNumericValue],
        ['sortLevelsAscending', sortLevelsAscending],
        ['parseLevelTokens', parseLevelTokens],
        ['parseMasterOptions', parseMasterOptions],
        ['parseMasterLevels', parseMasterLevels],
        ['normalizeEffectLevelPlaceholders', normalizeEffectLevelPlaceholdersFromUtils],
        ['normalizeRelicTypeColumns', normalizeRelicTypeColumns],
        ['parseTagTokens', parseTagTokens],
        ['formatTagTokens', formatTagTokens],
        ['serializeTagTokens', serializeTagTokens]
    ].filter(([, value]) => typeof value !== 'function');

    if (dataUtilsMissing.length) {
        const missingNames = dataUtilsMissing.map(([name]) => name).join(', ');
        throw new Error(`gallery data utilities are incomplete: missing ${missingNames}`);
    }

    function isNonePlaceholder(value) {
        if (value == null) {
            return false;
        }
        const text = String(value).trim();
        if (!text) {
            return false;
        }
        return text.toLowerCase() === 'none';
    }

    function toLevelOptionValue(value) {
        if (value == null) {
            return '';
        }
        return String(value).trim();
    }

    function formatLevelOptionLabel(value) {
        const text = toLevelOptionValue(value);
        return text && !isNonePlaceholder(text) ? text : '';
    }

    function buildLevelOptionsDisplay(values) {
        if (!Array.isArray(values)) {
            return '';
        }
        const displayValues = values
            .map((value) => formatLevelOptionLabel(value))
            .filter((value) => value !== '');
        return displayValues.join('|');
    }

    const normalizeEffectLevelPlaceholdersRecords = (records) =>
        normalizeEffectLevelPlaceholdersFromUtils(records);

    function parseJsonObject(jsonText) {
        if (typeof jsonText !== 'string') {
            return {};
        }
        try {
            const parsed = JSON.parse(jsonText);
            if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
                return parsed;
            }
        } catch (error) {
            console.warn('JSONの解析に失敗しました:', error);
        }
        return {};
    }

    function parseMasterOptionsByTypeJson(jsonText) {
        const result = {};
        const source = parseJsonObject(jsonText);
        Object.keys(source).forEach((key) => {
            const normalizedType = normalizeRelicTypeValue(key);
            if (!normalizedType || normalizedType === RELIC_TYPE_MERGED) {
                return;
            }
            const raw = source[key];
            if (!Array.isArray(raw)) {
                return;
            }
            const sanitized = raw
                .map((value) => {
                    if (typeof value === 'string') {
                        return value.trim();
                    }
                    return '';
                })
                .filter((value) => value);
            if (sanitized.length) {
                result[normalizedType] = Array.from(new Set(sanitized));
            }
        });
        return result;
    }

    function parseMasterLevelsByTypeJson(jsonText) {
        const result = {};
        const source = parseJsonObject(jsonText);
        Object.keys(source).forEach((key) => {
            const normalizedType = normalizeRelicTypeValue(key);
            if (!normalizedType || normalizedType === RELIC_TYPE_MERGED) {
                return;
            }
            const parsed = parseMasterLevels(source[key]);
            if (parsed instanceof Map && parsed.size) {
                result[normalizedType] = parsed;
            }
        });
        return result;
    }

    function parseMasterCsvByTypeJson(jsonText) {
        const result = {};
        const source = parseJsonObject(jsonText);
        Object.keys(source).forEach((key) => {
            const normalizedType = normalizeRelicTypeValue(key);
            if (!normalizedType || normalizedType === RELIC_TYPE_MERGED) {
                return;
            }
            const value = source[key];
            if (typeof value === 'string' && value.trim()) {
                result[normalizedType] = value.trim();
            }
        });
        return result;
    }

    function parseMasterDemeritRulesByTypeJson(jsonText) {
        const result = {};
        const source = parseJsonObject(jsonText);
        Object.keys(source).forEach((key) => {
            const normalizedType = normalizeRelicTypeValue(key);
            if (!normalizedType || normalizedType === RELIC_TYPE_MERGED) {
                return;
            }
            const value = source[key];
            if (!value || typeof value !== 'object') {
                return;
            }
            const normalizedEntries = {};
            Object.keys(value).forEach((effectKey) => {
                const normalizedEffectKey =
                    typeof effectKey === 'string' ? effectKey.trim().toLowerCase() : '';
                if (!normalizedEffectKey) {
                    return;
                }
                const entry = value[effectKey];
                if (!entry || typeof entry !== 'object') {
                    return;
                }
                const hasDemerit = Boolean(entry.hasDemerit);
                const levels = Array.isArray(entry.levels)
                    ? entry.levels
                          .map((level) => {
                              if (level == null) {
                                  return '';
                              }
                              const text = String(level).trim();
                              return text;
                          })
                          .filter((level) => level)
                    : [];
                normalizedEntries[normalizedEffectKey] = {
                    hasDemerit,
                    levels,
                };
            });
            if (Object.keys(normalizedEntries).length) {
                result[normalizedType] = normalizedEntries;
            }
        });
        return result;
    }

    function cloneLevelsMap(levels) {
        if (!(levels instanceof Map)) {
            return null;
        }
        const clone = new Map();
        levels.forEach((value, key) => {
            if (Array.isArray(value)) {
                clone.set(key, value.slice());
            } else {
                clone.set(key, []);
            }
        });
        return clone;
    }

    function cloneDemeritRulesMap(rules) {
        if (!rules || typeof rules !== 'object') {
            return {};
        }
        const clone = {};
        Object.keys(rules).forEach((key) => {
            const entry = rules[key];
            if (!entry || typeof entry !== 'object') {
                return;
            }
            const levels = Array.isArray(entry.levels) ? entry.levels.slice() : [];
            clone[key] = {
                hasDemerit: Boolean(entry.hasDemerit),
                levels,
            };
        });
        return clone;
    }

    function normalizeRelicTypeValue(value) {
        if (value == null) {
            return '';
        }
        const text = String(value).trim().toLowerCase();
        if (!text) {
            return '';
        }
        if (text === 'none') {
            return '';
        }
        if (text === 'normal' || text === '通常' || text === '通常遺物') {
            return 'normal';
        }
        if (text === 'deep' || text === '深層' || text === '深層遺物') {
            return 'deep';
        }
        if (text === 'merged' || text === 'all' || text === '統合') {
            return RELIC_TYPE_MERGED;
        }
        return text;
    }

    function sanitizeViewBoxValue(value) {
        if (typeof value !== 'string') {
            return '';
        }
        let text = value.trim();
        if (!text) {
            return '';
        }
        text = text.replace(/[\r\n]+/g, ' ');
        if (!text || VIEW_BOX_INVALID_PATTERN.test(text)) {
            return '';
        }
        if (text.length > VIEW_BOX_MAX_LENGTH) {
            text = text.slice(0, VIEW_BOX_MAX_LENGTH);
        }
        return text;
    }

    function splitInsetArguments(value) {
        if (typeof value !== 'string') {
            return [];
        }
        const [main] = value.split(/\s+round\b/i);
        const result = [];
        let current = '';
        let depth = 0;
        for (let i = 0; i < main.length; i += 1) {
            const char = main[i];
            if (char === '(') {
                depth += 1;
                current += char;
                continue;
            }
            if (char === ')') {
                if (depth > 0) {
                    depth -= 1;
                }
                current += char;
                continue;
            }
            if ((char === ' ' || char === '\t') && depth === 0) {
                const trimmed = current.trim();
                if (trimmed) {
                    result.push(trimmed);
                }
                current = '';
                continue;
            }
            current += char;
        }
        const trimmed = current.trim();
        if (trimmed) {
            result.push(trimmed);
        }
        return result;
    }

    function normalizeInsetValues(values) {
        if (!Array.isArray(values) || !values.length) {
            return null;
        }
        if (values.length === 1) {
            const [all] = values;
            return [all, all, all, all];
        }
        if (values.length === 2) {
            const [vertical, horizontal] = values;
            return [vertical, horizontal, vertical, horizontal];
        }
        if (values.length === 3) {
            const [top, horizontal, bottom] = values;
            return [top, horizontal, bottom, horizontal];
        }
        if (values.length >= 4) {
            return values.slice(0, 4);
        }
        return null;
    }

    function parseViewBoxComponents(value) {
        const sanitized = sanitizeViewBoxValue(value);
        if (!sanitized) {
            return null;
        }
        const match = sanitized.match(/^inset\((.+)\)$/i);
        if (!match) {
            return null;
        }
        const args = splitInsetArguments(match[1]);
        const normalized = normalizeInsetValues(args);
        if (!normalized) {
            return null;
        }
        return {
            top: normalized[0],
            right: normalized[1],
            bottom: normalized[2],
            left: normalized[3]
        };
    }

    function parseLengthValue(value) {
        if (typeof value !== 'string') {
            return null;
        }
        const match = value.trim().match(/^(-?\d+(?:\.\d+)?)([a-z%]*)$/i);
        if (!match) {
            return null;
        }
        return {
            value: Number.parseFloat(match[1]),
            unit: match[2] || ''
        };
    }

    function detectCommonUnit(lengths) {
        if (!lengths) {
            return '';
        }
        const keys = ['top', 'right', 'bottom', 'left'];
        const units = keys
            .map((key) => (lengths[key] && lengths[key].unit ? lengths[key].unit : ''))
            .filter((unit) => unit);
        if (!units.length) {
            return '';
        }
        return units.every((unit) => unit === units[0]) ? units[0] : units[0];
    }

    function createViewBoxStorageKey(basePath) {
        const source = typeof basePath === 'string' ? basePath.trim() : '';
        if (!source) {
            return VIEW_BOX_STORAGE_PREFIX;
        }
        return `${VIEW_BOX_STORAGE_PREFIX}:${source}`;
    }

    function readStoredViewBox(key) {
        if (typeof window === 'undefined' || !window.localStorage || !key) {
            return '';
        }
        try {
            return window.localStorage.getItem(key) || '';
        } catch (error) {
            console.warn('object-view-boxの読み込みに失敗しました:', error);
            return '';
        }
    }

    function writeStoredViewBox(key, value) {
        if (typeof window === 'undefined' || !window.localStorage || !key) {
            return;
        }
        try {
            if (!value) {
                window.localStorage.removeItem(key);
            } else {
                window.localStorage.setItem(key, value);
            }
        } catch (error) {
            console.warn('object-view-boxの保存に失敗しました:', error);
        }
    }

    const storageUtils = window.galleryStorageUtils || null;

    if (!storageUtils) {
        throw new Error('gallery storage utilities are not available');
    }

    const {
        parseCsvRecords,
        loadMergedRecords,
        createDuplicateManager
    } = storageUtils;

    const storageUtilsMissing = [
        ['parseCsvRecords', parseCsvRecords],
        ['loadMergedRecords', loadMergedRecords],
        ['createDuplicateManager', createDuplicateManager]
    ].filter(([, value]) => typeof value !== 'function');

    if (storageUtilsMissing.length) {
        const missingNames = storageUtilsMissing.map(([name]) => name).join(', ');
        throw new Error(`gallery storage utilities are incomplete: missing ${missingNames}`);
    }

    function normalizeStatus(value) {
        const text = (value || '').toString().trim().toLowerCase();
        if (text === 'none') {
            return 'none';
        }
        if (text === 'pass') {
            return 'pass';
        }
        if (text === 'corrected') {
            return 'corrected';
        }
        return 'pending';
    }

    function statusLabel(status) {
        if (status === 'none') {
            return '対象外';
        }
        if (status === 'pass') {
            return '確認済み';
        }
        if (status === 'corrected') {
            return '修正済み';
        }
        return '未レビュー';
    }

    function parseMasterLevelsCsv(text) {
        const map = new Map();
        if (!text) {
            return map;
        }
        const records = parseCsvRecords(text);
        if (!Array.isArray(records)) {
            return map;
        }
        records.forEach((record) => {
            if (!record || typeof record !== 'object') {
                return;
            }
            const name =
                record.EffectBase ||
                record.effect ||
                record.Name ||
                record.name ||
                record.label ||
                '';
            const key = effectKey(name);
            if (!key) {
                return;
            }
            const levelsSource =
                record.Levels ||
                record.levels ||
                record.Values ||
                record.values ||
                record.options ||
                record.candidates ||
                '';
            const tokens = parseLevelTokens(levelsSource);
            const sanitized = sanitizeLevelList(tokens);
            if (!sanitized.length) {
                return;
            }
            const existing = map.get(key) || [];
            const merged = Array.from(new Set(existing.concat(sanitized)));
            if (merged.length) {
                map.set(key, sortLevelsAscending(merged));
            }
        });
        return map;
    }

    function setupMasterOptions() {
        const current = Array.isArray(state.masterOptions) ? state.masterOptions : [];
        const normalized = current
            .map((value) => normalizeEffectName(value))
            .filter((value) => value);
        const unique = Array.from(new Set(normalized));
        stateApi.setMasterOptions(unique);
    }

    function setupMasterDemeritOptions() {
        const current = Array.isArray(state.masterDemeritOptions) ? state.masterDemeritOptions : [];
        const normalized = current
            .map((value) => normalizeEffectName(value))
            .filter((value) => value);
        const unique = Array.from(new Set(normalized));
        stateApi.setMasterDemeritOptions(unique);
    }

    function isMasterOptionValue(value, options) {
        if (!options || !Array.isArray(options) || !options.length) {
            return true;
        }
        const normalized = effectKey(value);
        if (!normalized) {
            return false;
        }
        for (let index = 0; index < options.length; index += 1) {
            const candidate = options[index];
            if (effectKey(candidate) === normalized) {
                return true;
            }
        }
        return false;
    }

    function validateMasterEffectValue(value) {
        return isMasterOptionValue(value, state.masterOptions);
    }

    function validateMasterDemeritValue(value) {
        return isMasterOptionValue(value, state.masterDemeritOptions);
    }

    function ensureMasterDatalist() {
        if (typeof document === 'undefined') {
            return;
        }
        let datalist = document.getElementById(MASTER_DATALIST_ID);
        if (!datalist) {
            datalist = document.createElement('datalist');
            datalist.id = MASTER_DATALIST_ID;
            document.body.appendChild(datalist);
        }
        datalist.textContent = '';
        state.masterOptions.forEach((option) => {
            const optionNode = document.createElement('option');
            optionNode.value = option;
            datalist.appendChild(optionNode);
        });
        stateApi.markMasterDatalistPrepared(true);
    }

    function ensureMasterDemeritDatalist() {
        if (typeof document === 'undefined') {
            return;
        }
        let datalist = document.getElementById(MASTER_DEMERIT_DATALIST_ID);
        if (!datalist) {
            datalist = document.createElement('datalist');
            datalist.id = MASTER_DEMERIT_DATALIST_ID;
            document.body.appendChild(datalist);
        }
        datalist.textContent = '';
        state.masterDemeritOptions.forEach((option) => {
            const optionNode = document.createElement('option');
            optionNode.value = option;
            datalist.appendChild(optionNode);
        });
        stateApi.markMasterDemeritDatalistPrepared(true);
    }

    async function ensureMasterOptions() {
        if (state.masterDatalistPrepared) {
            return;
        }
        if (!state.masterJsonPath) {
            setupMasterOptions();
            ensureMasterDatalist();
            return;
        }
        try {
            const response = await fetch(state.masterJsonPath, { cache: 'no-cache' });
            if (!response.ok) {
                throw new Error(`HTTP ${response.status}`);
            }
            const data = await response.json();
            stateApi.setMasterOptions(parseMasterOptions(data));
        } catch (error) {
            console.error('マスターデータの読み込みに失敗しました:', error);
            setStorageStatus(`マスターデータの読み込みに失敗しました: ${error.message || error}`, true);
            stateApi.setMasterOptions([]);
        }
        setupMasterOptions();
        ensureMasterDatalist();
    }

    async function ensureMasterDemeritOptions() {
        if (state.masterDemeritDatalistPrepared) {
            return;
        }
        if (!state.masterDemeritJsonPath) {
            setupMasterDemeritOptions();
            ensureMasterDemeritDatalist();
            return;
        }
        try {
            const response = await fetch(state.masterDemeritJsonPath, { cache: 'no-cache' });
            if (!response.ok) {
                throw new Error(`HTTP ${response.status}`);
            }
            const data = await response.json();
            stateApi.setMasterDemeritOptions(parseMasterOptions(data));
        } catch (error) {
            console.error('デメリットマスターデータの読み込みに失敗しました:', error);
            setStorageStatus(
                `デメリットマスターデータの読み込みに失敗しました: ${error.message || error}`,
                true
            );
            stateApi.setMasterDemeritOptions([]);
        }
        setupMasterDemeritOptions();
        ensureMasterDemeritDatalist();
    }

    async function ensureMasterLevels() {
        if (state.masterLevelsLoaded) {
            return;
        }
        if (state.masterLevelsPromise) {
            await state.masterLevelsPromise;
            return;
        }

        const loader = (async () => {
            try {
                const csvPath = state.masterCsvPath;
                if (!csvPath) {
                    stateApi.setMasterLevels(null);
                    return;
                }
                const response = await fetch(csvPath, { cache: 'no-cache' });
                if (!response.ok) {
                    throw new Error(`HTTP ${response.status}`);
                }
                const csvText = await response.text();
                stateApi.setMasterLevels(parseMasterLevelsCsv(csvText));
            } catch (error) {
                console.warn('レベル候補の読み込みに失敗しました:', error);
                stateApi.setMasterLevels(null);
            } finally {
                stateApi.setMasterLevelsLoaded(true);
                stateApi.clearMasterLevelsPromise();
            }
        })();

        stateApi.setMasterLevelsPromise(loader);
        await loader;
    }

    function applyMasterLevelOptions(effect, select, effectName, helpers = {}) {
        if (!effect || !select) {
            return;
        }
        const {
            setCorrectionLevelCandidates: setCandidatesHelper,
            rebuildLevelSelectOptions: rebuildOptionsHelper,
            onOptionsApplied: onOptionsAppliedHelper,
            sanitizeLevelList: sanitizeLevelListHelper,
            sortLevelsAscending: sortLevelsAscendingHelper
        } = helpers || {};

        const setCandidates =
            typeof setCandidatesHelper === 'function'
                ? setCandidatesHelper
                : (targetEffect, candidates) => {
                      const sanitized = sanitizeLevelList(candidates);
                      if (targetEffect) {
                          targetEffect.dataset.levelOptionsBaseJson = JSON.stringify(sanitized);
                      }
                      return sanitized;
                  };

        const rebuildOptions =
            typeof rebuildOptionsHelper === 'function'
                ? rebuildOptionsHelper
                : (targetEffect, targetSelect, baseOptions) => {
                      const values = Array.isArray(baseOptions) ? baseOptions : [];
                      targetSelect.textContent = '';
                      const hasNonePlaceholder = values.some((value) => isNonePlaceholder(value));
                      if (!hasNonePlaceholder) {
                          const emptyOption = document.createElement('option');
                          emptyOption.value = '';
                          emptyOption.textContent = '';
                          targetSelect.appendChild(emptyOption);
                      }
                      values.forEach((value) => {
                          const valueText = toLevelOptionValue(value);
                          if (!valueText) {
                              return;
                          }
                          const optionNode = document.createElement('option');
                          optionNode.value = valueText;
                          optionNode.textContent = formatLevelOptionLabel(valueText);
                          targetSelect.appendChild(optionNode);
                      });
                      if (targetEffect) {
                          targetEffect.dataset.levelOptionsDisplay = buildLevelOptionsDisplay(values);
                      }
                  };

        const sanitizeList =
            typeof sanitizeLevelListHelper === 'function'
                ? sanitizeLevelListHelper
                : sanitizeLevelList;
        const sortList =
            typeof sortLevelsAscendingHelper === 'function'
                ? sortLevelsAscendingHelper
                : sortLevelsAscending;
        const notifyApplied =
            typeof onOptionsAppliedHelper === 'function'
                ? (targetEffect, applied) => onOptionsAppliedHelper(targetEffect, applied)
                : null;

        const applyOptions = (targetEffect, optionsList) => {
            const sanitized = sanitizeList(Array.isArray(optionsList) ? optionsList : []);
            const sorted = sortList(sanitized);
            if (targetEffect) {
                targetEffect.dataset.levelOptionsBaseJson = JSON.stringify(sorted);
            }
            rebuildOptions(targetEffect, select, sorted);
            if (notifyApplied) {
                notifyApplied(targetEffect, sorted);
            }
        };

        const normalizedName = normalizeEffectName(effectName);
        if (!state.masterLevelsLoaded) {
            setCandidates(effect, []);
            applyOptions(effect, []);
            void ensureMasterLevels().then(() => {
                applyMasterLevelOptions(effect, select, normalizedName, helpers);
            });
            return;
        }

        const levelsMap = state.masterLevels instanceof Map ? state.masterLevels : null;
        if (!levelsMap) {
            setCandidates(effect, []);
            applyOptions(effect, []);
            return;
        }

        const key = effectKey(normalizedName);
        if (!key) {
            setCandidates(effect, []);
            applyOptions(effect, []);
            return;
        }

        const candidates = levelsMap.get(key) || [];
        const applied = setCandidates(effect, candidates);
        applyOptions(effect, applied);
    }

    const datasets = parseDatasets(datasetsJson);
    const activeDatasetIndex = parseDatasetIndex(activeDatasetAttr, datasets.length);
    const preloadedMasterLevels = parseMasterLevels(masterLevelsJson);
    const hasPreloadedMasterLevels = preloadedMasterLevels instanceof Map && preloadedMasterLevels.size > 0;
    const masterOptionsByType = parseMasterOptionsByTypeJson(masterOptionsMapJson);
    const masterLevelsByType = parseMasterLevelsByTypeJson(masterLevelsMapJson);
    const masterCsvByType = parseMasterCsvByTypeJson(masterCsvMapJson);
    const masterDemeritOptionsByType = parseMasterOptionsByTypeJson(masterDemeritOptionsMapJson);
    const masterDemeritCsvByType = parseMasterCsvByTypeJson(masterDemeritCsvMapJson);
    const masterDemeritRulesByType = parseMasterDemeritRulesByTypeJson(masterDemeritRulesMapJson);

    const dom = {
        gallery: document.getElementById('gallery'),
        datasetSelector: document.getElementById('dataset-selector'),
        datasetSelect: document.getElementById('dataset-select'),
        relicTypeSelect: document.getElementById('relic-type-select'),
        galleryStatus: document.getElementById('gallery-status'),
        searchInput: document.getElementById('search-input'),
        effectSearchInputs: [
            document.getElementById('effect-search-1'),
            document.getElementById('effect-search-2'),
            document.getElementById('effect-search-3')
        ].filter(Boolean),
        effectSearchModes: Array.from(document.querySelectorAll('.effect-search-mode-select')),
        tagSearchInput: document.getElementById('tag-search-input'),
        filterSelect: document.getElementById('filter-status'),
        colorFilter: document.getElementById('filter-color'),
        showDuplicatesToggle: document.getElementById('show-duplicates'),
        showOcrToggle: document.getElementById('show-ocr'),
        lightbox: document.getElementById('lightbox'),
        lightboxImg: document.querySelector('#lightbox img'),
        lightboxClose: document.getElementById('lightbox-close'),
        downloadCsvButton: document.getElementById('download-csv'),
        uploadCsvButton: document.getElementById('upload-csv'),
        uploadCsvInput: document.getElementById('upload-csv-input'),
        storageStatus: document.getElementById('storage-status'),
        summary: document.getElementById('gallery-summary'),
        viewBoxContainer: document.getElementById('viewbox-controls'),
        viewBoxTopInput: document.getElementById('viewbox-top'),
        viewBoxLeftInput: document.getElementById('viewbox-left'),
        viewBoxHeightInput: document.getElementById('viewbox-height'),
        viewBoxWidthInput: document.getElementById('viewbox-width'),
        viewBoxApplyButton: document.getElementById('viewbox-apply'),
        viewBoxResetButton: document.getElementById('viewbox-reset')
    };

    const viewBoxStorageKey = createViewBoxStorageKey(initialCsvPath);

    let activeRelicType = RELIC_TYPE_ALL;

    if (dom.uploadCsvButton) {
        dom.uploadCsvButton.disabled = true;
        dom.uploadCsvButton.title = 'ローカルCSVのインポートは無効化されています';
    }

    setupViewBoxControls();

    if (!dom.gallery) {
        return;
    }

    const stateStoreFactory = window.galleryStateStoreFactory || null;
    if (!stateStoreFactory || typeof stateStoreFactory.createStateStore !== 'function') {
        throw new Error('gallery state store factory is not available');
    }

    const stateStore = stateStoreFactory.createStateStore({

        datasets: Array.isArray(datasets) ? datasets.slice() : [],
        activeDatasetIndex: activeDatasetIndex,
        labelSymbols: parseLabelSymbols(labelSymbolsJson),
        imageDir: imageDir || '.',
        csvPath: initialCsvPath,
        masterCsvPath: masterCsvPath || '',
        masterJsonPath: masterJsonPath || '',
        masterOptions: parseMasterOptions(masterOptionsJson),
        masterDemeritCsvPath: masterDemeritCsvPath || '',
        masterDemeritJsonPath: masterDemeritJsonPath || '',
        masterDemeritOptions: parseMasterOptions(masterDemeritOptionsJson),
        masterDemeritRules: {},
        masterLevels: preloadedMasterLevels,
        masterLevelsLoaded: hasPreloadedMasterLevels
    });

    const appStateFactory = window.galleryAppStateFactory || null;
    if (!appStateFactory || typeof appStateFactory.createStateApi !== 'function') {
        throw new Error('gallery app state factory is not available');
    }

    const stateApi = appStateFactory.createStateApi({ stateStore });
    const { state, datasetState } = stateApi;

    const recordUtilsFactory = window.galleryRecordUtilsFactory || null;
    const recordUtils =
        (recordUtilsFactory && typeof recordUtilsFactory.createRecordUtils === 'function'
            ? recordUtilsFactory.createRecordUtils()
            : window.galleryRecordUtils) || null;

    if (!recordUtils) {
        throw new Error('gallery record utilities are not available');
    }
    setupMasterOptions();
    setupMasterDemeritOptions();
    if (!state.masterJsonPath && state.masterOptions.length) {
        ensureMasterDatalist();
    }
    if (!state.masterDemeritJsonPath && state.masterDemeritOptions.length) {
        ensureMasterDemeritDatalist();
    }

    const defaultMasterOptions = Array.isArray(state.masterOptions) ? state.masterOptions.slice() : [];
    const defaultMasterLevelsMap = cloneLevelsMap(preloadedMasterLevels);
    const defaultMasterCsvPath = state.masterCsvPath || '';
    const defaultMasterJsonPath = state.masterJsonPath || '';
    const defaultMasterDemeritOptions = Array.isArray(state.masterDemeritOptions)
        ? state.masterDemeritOptions.slice()
        : [];
    const defaultMasterDemeritCsvPath = state.masterDemeritCsvPath || '';
    const defaultMasterDemeritJsonPath = state.masterDemeritJsonPath || '';

    function handleStateChange() {
        updateDatasetIndicator();
        updateSaveAvailability();
    }

    const datasetManagerFactory = window.galleryDatasetManagerFactory || null;
    if (!datasetManagerFactory || typeof datasetManagerFactory.createDatasetManager !== 'function') {
        throw new Error('gallery dataset manager factory is not available');
    }

    const clearGalleryForReload = () => {
        clearElementChildren(dom.gallery);
        stateApi.clearRecordsAndItems();
    };

    const datasetManager = datasetManagerFactory.createDatasetManager({
        stateStore,
        datasetState,
        state,
        resolveDatasetState,
        areSourcesEqual,
        applyDatasetState,
        clearForReload: clearGalleryForReload,
        loadInitialData: () => loadInitialData()
    });

    const { clampDatasetIndex, getCurrentDataset, prepareInitialDataset, switchDataset } = datasetManager;

    function getDatasetRelicType(dataset) {
        if (!dataset) {
            return '';
        }
        return normalizeRelicTypeValue(dataset.relicType || '');
    }

    function getAvailableRelicTypes() {
        const types = new Set();
        if (!Array.isArray(datasetState.list)) {
            return types;
        }
        datasetState.list.forEach((dataset) => {
            const type = getDatasetRelicType(dataset);
            if (type && type !== RELIC_TYPE_MERGED) {
                types.add(type);
            }
        });
        return types;
    }

    function getFilteredDatasetIndexes(filterType) {
        const list = Array.isArray(datasetState.list) ? datasetState.list : [];
        if (!list.length) {
            return [];
        }
        const normalized = filterType === RELIC_TYPE_ALL ? RELIC_TYPE_ALL : normalizeRelicTypeValue(filterType);
        if (normalized === RELIC_TYPE_ALL) {
            return list.map((_, index) => index);
        }
        const indexes = [];
        list.forEach((dataset, index) => {
            const type = getDatasetRelicType(dataset);
            if (type === normalized) {
                indexes.push(index);
            }
        });
        return indexes;
    }

    function updateRelicTypeSelector() {
        if (!dom.relicTypeSelect) {
            return;
        }
        const availableTypes = Array.from(getAvailableRelicTypes());
        if (availableTypes.length <= 1) {
            activeRelicType = RELIC_TYPE_ALL;
            clearElementChildren(dom.relicTypeSelect);
            dom.relicTypeSelect.value = RELIC_TYPE_ALL;
            dom.relicTypeSelect.title = RELIC_TYPE_LABELS[RELIC_TYPE_ALL];
            setElementHidden(dom.relicTypeSelect, true);
            return;
        }

        const options = [RELIC_TYPE_ALL, ...availableTypes];
        const needsRebuild =
            dom.relicTypeSelect.options.length !== options.length ||
            options.some((type, index) => dom.relicTypeSelect.options[index].value !== type);

        if (needsRebuild) {
            clearElementChildren(dom.relicTypeSelect);
            options.forEach((type) => {
                const option = document.createElement('option');
                option.value = type;
                option.textContent = RELIC_TYPE_LABELS[type] || type;
                dom.relicTypeSelect.appendChild(option);
            });
        }

        if (!options.includes(activeRelicType)) {
            activeRelicType = RELIC_TYPE_ALL;
        }

        dom.relicTypeSelect.value = activeRelicType;
        dom.relicTypeSelect.title = RELIC_TYPE_LABELS[activeRelicType] || activeRelicType;
        setElementHidden(dom.relicTypeSelect, false);
    }

    function rebuildDatasetOptions(selectedIndex) {
        if (!dom.datasetSelector || !dom.datasetSelect) {
            return;
        }
        const indexes = getFilteredDatasetIndexes(activeRelicType);
        clearElementChildren(dom.datasetSelect);
        if (!indexes.length) {
            setElementHidden(dom.datasetSelector, true);
            return;
        }
        indexes.forEach((datasetIndex) => {
            const option = document.createElement('option');
            option.value = String(datasetIndex);
            option.textContent = datasetOptionLabel(datasetState.list[datasetIndex], datasetIndex);
            dom.datasetSelect.appendChild(option);
        });
        const normalizedSelected = indexes.includes(selectedIndex) ? selectedIndex : indexes[0];
        dom.datasetSelect.value = String(normalizedSelected);
        dom.datasetSelect.title = datasetOptionLabel(datasetState.list[normalizedSelected], normalizedSelected);
        setElementHidden(dom.datasetSelector, false);
    }

    function applyMasterDataForType(relicType) {
        const normalizedType = normalizeRelicTypeValue(relicType);
        const lookupKey = normalizedType && normalizedType !== RELIC_TYPE_MERGED ? normalizedType : '';

        const nextOptions = lookupKey && Array.isArray(masterOptionsByType[lookupKey])
            ? masterOptionsByType[lookupKey].slice()
            : defaultMasterOptions.slice();
        stateApi.setMasterOptions(nextOptions);
        setupMasterOptions();
        stateApi.markMasterDatalistPrepared(false);
        ensureMasterDatalist();

        const nextDemeritOptions = lookupKey && Array.isArray(masterDemeritOptionsByType[lookupKey])
            ? masterDemeritOptionsByType[lookupKey].slice()
            : defaultMasterDemeritOptions.slice();
        stateApi.setMasterDemeritOptions(nextDemeritOptions);
        setupMasterDemeritOptions();
        stateApi.markMasterDemeritDatalistPrepared(false);
        ensureMasterDemeritDatalist();

        const nextDemeritRules =
            lookupKey && typeof masterDemeritRulesByType[lookupKey] === 'object'
                ? masterDemeritRulesByType[lookupKey]
                : {};
        stateApi.setMasterDemeritRules(cloneDemeritRulesMap(nextDemeritRules));

        let nextLevels = null;
        if (lookupKey && masterLevelsByType[lookupKey] instanceof Map) {
            nextLevels = cloneLevelsMap(masterLevelsByType[lookupKey]);
        }
        if (!nextLevels) {
            nextLevels = cloneLevelsMap(defaultMasterLevelsMap);
        }

        if (nextLevels) {
            stateApi.setMasterLevels(nextLevels);
            stateApi.setMasterLevelsLoaded(true);
        } else {
            stateApi.setMasterLevels(null);
            stateApi.setMasterLevelsLoaded(false);
        }
        stateApi.clearMasterLevelsPromise();

        let nextCsvPath = defaultMasterCsvPath;
        if (lookupKey && typeof masterCsvByType[lookupKey] === 'string') {
            const candidate = masterCsvByType[lookupKey].trim();
            if (candidate) {
                nextCsvPath = candidate;
            }
        }
        const resolvedCsvPath = normalizedType === RELIC_TYPE_MERGED ? defaultMasterCsvPath : nextCsvPath;

        let nextDemeritCsvPath = defaultMasterDemeritCsvPath;
        if (lookupKey && typeof masterDemeritCsvByType[lookupKey] === 'string') {
            const candidate = masterDemeritCsvByType[lookupKey].trim();
            if (candidate) {
                nextDemeritCsvPath = candidate;
            }
        }
        const resolvedDemeritCsvPath =
            normalizedType === RELIC_TYPE_MERGED ? defaultMasterDemeritCsvPath : nextDemeritCsvPath;

        stateStore.update({
            core: {
                masterCsvPath: resolvedCsvPath || '',
                masterJsonPath: defaultMasterJsonPath,
                masterDemeritCsvPath: resolvedDemeritCsvPath || '',
                masterDemeritJsonPath: defaultMasterDemeritJsonPath
            }
        });
    }

    function isNoneValue(value) {
        if (value == null) {
            return true;
        }
        const text = String(value).trim();
        if (!text) {
            return true;
        }
        return text.toLowerCase() === 'none';
    }

    function normalizeLevelOptionsForRecord(options) {
        const list = Array.isArray(options) ? options : [];
        const sanitized = sanitizeLevelList(list);
        const unique = [];
        const seen = new Set();
        sanitized.forEach((value) => {
            if (value == null) {
                return;
            }
            const text = String(value).trim();
            if (!text) {
                return;
            }
            const key = text.toLowerCase();
            if (seen.has(key)) {
                return;
            }
            seen.add(key);
            unique.push(text);
        });
        const sorted = sortLevelsAscending(unique);
        const serialized = sorted.length ? sorted.join('|') : 'none';
        return { sorted, serialized };
    }

    function syncRecordLevelOptions(effect, options) {
        if (!effect || typeof getEffectIndexes !== 'function') {
            return false;
        }
        const indexes = getEffectIndexes(effect);
        if (!indexes || indexes.kind === 'demerit') {
            return false;
        }

        const { sorted, serialized } = normalizeLevelOptionsForRecord(options);
        const optionsChanged = updateRecordLevelOptions(
            indexes.recordIndex,
            indexes.slotIndex,
            serialized,
            indexes.kind
        );

        let levelChanged = false;
        if (!sorted.length || sorted.every((value) => isNoneValue(value))) {
            levelChanged = updateRecordLevelValue(indexes.recordIndex, indexes.slotIndex, 'none', indexes.kind);
            if (effect.dataset) {
                effect.dataset.level = '';
            }
        } else {
            const normalizeLevelForComparison = (value) => {
                if (value == null) {
                    return 'none';
                }
                const text = String(value).trim();
                if (!text) {
                    return 'none';
                }
                return text.toLowerCase();
            };

            const normalizedOptions = sorted.map((value) => normalizeLevelForComparison(value));
            const record = getRecordByIndex(indexes.recordIndex);
            const levelKey = `Effect${indexes.slotIndex}Level`;
            let currentLevel = 'none';
            if (record && Object.prototype.hasOwnProperty.call(record, levelKey)) {
                const rawLevel = record[levelKey];
                if (rawLevel != null) {
                    const text = String(rawLevel).trim();
                    currentLevel = text || 'none';
                }
            }
            const normalizedCurrent = normalizeLevelForComparison(currentLevel);
            if (!normalizedOptions.includes(normalizedCurrent)) {
                const hasNoneOption = normalizedOptions.includes('none');
                const nextLevel = hasNoneOption ? 'none' : sorted[0];
                const updated = updateRecordLevelValue(
                    indexes.recordIndex,
                    indexes.slotIndex,
                    nextLevel,
                    indexes.kind
                );
                if (updated) {
                    levelChanged = true;
                    if (effect.dataset) {
                        effect.dataset.level = nextLevel === 'none' ? '' : String(nextLevel).trim().toLowerCase();
                    }
                }
            }
        }

        if (effect.dataset) {
            effect.dataset.levelOptionsBaseJson = JSON.stringify(sorted);
        }

        if (optionsChanged || levelChanged) {
            storageManager.scheduleSave();
        }

        return optionsChanged || levelChanged;
    }

    function applyMasterDataForRelicType(relicType, context = {}) {
        const requested = normalizeRelicTypeValue(relicType);
        const fallback = normalizeRelicTypeValue(datasetState.relicType || '');
        const targetType = requested || fallback || '';

        applyMasterDataForType(targetType);

        const { item } = context || {};
        if (!item || typeof item.querySelectorAll !== 'function') {
            return;
        }

        const effects = item.querySelectorAll('.effect');
        effects.forEach((effect) => {
            if (!effect || typeof effect.querySelector !== 'function') {
                return;
            }
            const levelInput = effect.querySelector('.level-input');
            if (!levelInput) {
                if (
                    effect.dataset &&
                    effect.dataset.kind === 'demerit' &&
                    typeof syncDemeritAvailability === 'function'
                ) {
                    syncDemeritAvailability(effect, { refreshStatus: true });
                }
                return;
            }
            const correctionInput = effect.querySelector('.correction-input');
            const effectName =
                (correctionInput && typeof correctionInput.value === 'string' && correctionInput.value.trim()) ||
                effect.dataset.predictionValue ||
                effect.dataset.raw ||
                '';

            applyMasterLevelOptions(effect, levelInput, effectName, {
                setCorrectionLevelCandidates,
                rebuildLevelSelectOptions,
                sanitizeLevelList,
                sortLevelsAscending,
                onOptionsApplied: (targetEffect, options) => {
                    if (targetEffect !== effect) {
                        return false;
                    }
                    return syncRecordLevelOptions(targetEffect, options);
                }
            });

            const baseJson = effect.dataset.levelOptionsBaseJson || '';
            let baseOptions = [];
            if (baseJson) {
                try {
                    const parsed = JSON.parse(baseJson);
                    if (Array.isArray(parsed)) {
                        baseOptions = parsed;
                    }
                } catch (error) {
                    console.warn('レベル候補(base json)の解析に失敗しました:', error);
                }
            }
            syncRecordLevelOptions(effect, baseOptions);
            updateLevelInputAvailability(levelInput, baseOptions);

            if (
                effect.dataset &&
                effect.dataset.kind === 'demerit' &&
                typeof syncDemeritAvailability === 'function'
            ) {
                syncDemeritAvailability(effect, { refreshStatus: true });
            }
        });

        refreshItemCaches(item);
    }

    function setActiveRelicType(value) {
        const requested = value === RELIC_TYPE_ALL ? RELIC_TYPE_ALL : normalizeRelicTypeValue(value);
        const available = getAvailableRelicTypes();
        let nextType = requested;
        if (nextType !== RELIC_TYPE_ALL && !available.has(nextType)) {
            nextType = RELIC_TYPE_ALL;
        }
        if (nextType !== activeRelicType) {
            activeRelicType = nextType;
        }
        updateRelicTypeSelector();
        const indexes = getFilteredDatasetIndexes(activeRelicType);
        if (!indexes.length) {
            rebuildDatasetOptions(-1);
            return;
        }
        const currentIndex = clampDatasetIndex(datasetState.activeIndex);
        const targetIndex = indexes.includes(currentIndex) ? currentIndex : indexes[0];
        rebuildDatasetOptions(targetIndex);
        if (targetIndex !== currentIndex) {
            void switchDataset(targetIndex);
        }
    }

    const appFactory = window.galleryAppFactory || null;

    const createAppController =
        appFactory && typeof appFactory.createAppController === 'function'
            ? appFactory.createAppController
            : function createAppControllerFallback(config = {}) {
                  const {
                      attachEventHandlers: attachHandlers = () => {},
                      prepareInitialDataset: prepareDataset = () => {},
                      setupDatasetSelector: setupSelector = () => {},
                      ensureMasterLevels: loadMasterLevels = async () => {},
                      ensureMasterOptions: loadMasterOptions = async () => {},
                      ensureMasterDemeritOptions: loadMasterDemeritOptions = async () => {},
                      datasetState: dsState = { list: [], activeIndex: -1 },
                      switchDataset: switchFn = async () => {},
                      loadInitialData: loadData = async () => {}
                  } = config;

                  return {
                      async initialize() {
                          attachHandlers();
                          prepareDataset();
                          setupSelector();
                          await loadMasterLevels();
                          await loadMasterOptions();
                          await loadMasterDemeritOptions();
                          if (dsState && Array.isArray(dsState.list) && dsState.list.length) {
                              await switchFn(dsState.activeIndex, { forceReload: true });
                          } else {
                              await loadData();
                          }
                      }
                  };
              };

    function getRecordByIndex(index) {
        return recordUtils.getRecordByIndex(state.records, index);
    }

    const duplicateFlags = recordUtils.createFlagManager(
        () => state.records,
        DUPLICATE_KEY,
        ['true', '1', 'yes', 'duplicate']
    );
    const favoriteFlags = recordUtils.createFlagManager(
        () => state.records,
        FAVORITE_KEY,
        ['true', '1', 'yes', 'favorite']
    );

    function normalizeDuplicateFlag(value) {
        return duplicateFlags.normalize(value);
    }

    function isRecordDuplicate(record) {
        return duplicateFlags.isSet(record);
    }

    function setRecordDuplicate(recordIndex, isDuplicate) {
        return duplicateFlags.set(recordIndex, isDuplicate);
    }

    function normalizeFavoriteFlag(value) {
        return favoriteFlags.normalize(value);
    }

    function isRecordFavorite(record) {
        return favoriteFlags.isSet(record);
    }

    function setRecordFavorite(recordIndex, isFavorite) {
        return favoriteFlags.set(recordIndex, isFavorite);
    }

    function normalizeRecordRelicType(value) {
        const normalized = normalizeRelicTypeValue(value);
        if (normalized === 'normal' || normalized === 'deep') {
            return normalized;
        }
        return '';
    }

    function setRecordItemColor(recordIndex, colorKey) {
        const record = getRecordByIndex(recordIndex);
        if (!record) {
            return false;
        }
        const normalized = normalizeItemColor(colorKey);
        if (normalized) {
            if (record.ItemColor === normalized) {
                return false;
            }
            record.ItemColor = normalized;
            return true;
        }
        if (Object.prototype.hasOwnProperty.call(record, 'ItemColor')) {
            delete record.ItemColor;
            return true;
        }
        return false;
    }

    function setRecordItemRelicType(recordIndex, relicType) {
        const record = getRecordByIndex(recordIndex);
        if (!record) {
            return false;
        }
        const normalized = normalizeRecordRelicType(relicType);
        if (normalized) {
            if (record.RelicType === normalized) {
                return false;
            }
            record.RelicType = normalized;
            return true;
        }
        if (Object.prototype.hasOwnProperty.call(record, 'RelicType')) {
            delete record.RelicType;
            return true;
        }
        return false;
    }

    function normalizeRecordTags(value) {
        if (typeof formatTagTokens !== 'function') {
            return value == null ? '' : String(value).trim();
        }
        return formatTagTokens(value);
    }

    function serializeRecordTags(value) {
        if (typeof serializeTagTokens !== 'function') {
            return value == null ? '' : String(value).trim();
        }
        return serializeTagTokens(value);
    }

    function setRecordTags(recordIndex, tagsValue) {
        const record = getRecordByIndex(recordIndex);
        if (!record) {
            return false;
        }
        const normalized = normalizeRecordTags(tagsValue);
        let changed = false;
        if (normalized) {
            if (record.Tags === normalized) {
                return false;
            }
            record.Tags = normalized;
            changed = true;
        } else if (Object.prototype.hasOwnProperty.call(record, 'Tags')) {
            delete record.Tags;
            changed = true;
        }
        if (changed && typeof syncTagSearchOptions === 'function') {
            syncTagSearchOptions(state.records);
        }
        return changed;
    }

    function updateRecordField(recordIndex, key, value) {
        return recordUtils.updateRecordField(state.records, recordIndex, key, value);
    }

    function resolveCsvSavePath(csvPath) {
        if (!csvPath) {
            return '';
        }
        const trimmed = csvPath.trim();
        if (!trimmed) {
            return '';
        }
        try {
            const resolved = new URL(trimmed, window.location.href);
            const basePath = window.location.pathname.replace(/[^/]+$/, '');
            let relative = decodeURIComponent(resolved.pathname || '');
            if (basePath && relative.startsWith(basePath)) {
                relative = relative.slice(basePath.length);
            }
            if (!relative) {
                relative = trimmed;
            }
            return relative.replace(/^\/+/, '');
        } catch (error) {
            console.warn('CSVパスの解決に失敗しました:', error);
            return trimmed.replace(/^\/+/, '');
        }
    }

    function setupViewBoxControls() {
        const topInput = dom.viewBoxTopInput || null;
        const leftInput = dom.viewBoxLeftInput || null;
        const heightInput = dom.viewBoxHeightInput || null;
        const widthInput = dom.viewBoxWidthInput || null;
        const applyButton = dom.viewBoxApplyButton || null;
        const resetButton = dom.viewBoxResetButton || null;

        const rawDefault =
            (body.dataset && body.dataset.defaultItemImageViewBox) ||
            body.style.getPropertyValue('--item-image-view-box') ||
            '';
        const defaultValue = sanitizeViewBoxValue(rawDefault) || VIEW_BOX_FALLBACK;
        const rawStored = readStoredViewBox(viewBoxStorageKey);
        const storedValue = sanitizeViewBoxValue(rawStored);
        if (rawStored && !storedValue) {
            writeStoredViewBox(viewBoxStorageKey, '');
        }

        let initialValue = storedValue || defaultValue;
        let lastParsedLengths = null;
        let viewBoxUnit = '';
        let imageDimensions = null;

        function persistValue(value) {
            if (!value || value === defaultValue) {
                writeStoredViewBox(viewBoxStorageKey, '');
            } else {
                writeStoredViewBox(viewBoxStorageKey, value);
            }
        }

        function formatNumber(value) {
            if (!Number.isFinite(value)) {
                return '';
            }
            const rounded = Math.round(value * 1000) / 1000;
            if (Number.isInteger(rounded)) {
                return String(rounded);
            }
            return rounded.toFixed(3).replace(/0+$/, '').replace(/\.$/, '');
        }

        function setNumberInput(input, value) {
            if (!input) {
                return;
            }
            if (!Number.isFinite(value)) {
                input.value = '';
                return;
            }
            input.value = formatNumber(Math.max(0, value));
        }

        function ensureParsedLengths(value) {
            const components = parseViewBoxComponents(value);
            if (!components) {
                return null;
            }
            const keys = ['top', 'right', 'bottom', 'left'];
            const lengths = {};
            for (const key of keys) {
                const parsed = parseLengthValue(components[key]);
                if (!parsed || !Number.isFinite(parsed.value)) {
                    return null;
                }
                const normalizedUnit = parsed.unit || '';
                lengths[key] = {
                    value: parsed.value,
                    unit: normalizedUnit
                };
            }
            let detectedUnit = detectCommonUnit(lengths);
            if (!detectedUnit) {
                detectedUnit = viewBoxUnit || 'px';
            }
            if (!detectedUnit) {
                detectedUnit = 'px';
            }
            keys.forEach((key) => {
                lengths[key].unit = detectedUnit;
            });
            lastParsedLengths = lengths;
            viewBoxUnit = detectedUnit;
            return lengths;
        }

        function updateSizeInputs() {
            if (!widthInput || !heightInput) {
                return;
            }
            if (!imageDimensions || !lastParsedLengths) {
                setNumberInput(widthInput, Number.NaN);
                setNumberInput(heightInput, Number.NaN);
                return;
            }
            const widthValue = Math.max(
                imageDimensions.width - lastParsedLengths.left.value - lastParsedLengths.right.value,
                0
            );
            const heightValue = Math.max(
                imageDimensions.height - lastParsedLengths.top.value - lastParsedLengths.bottom.value,
                0
            );
            setNumberInput(widthInput, widthValue);
            setNumberInput(heightInput, heightValue);
        }

        function syncInputsFromParsedLengths(lengths) {
            if (!lengths) {
                return;
            }
            if (topInput) {
                setNumberInput(topInput, lengths.top.value);
            }
            if (leftInput) {
                setNumberInput(leftInput, lengths.left.value);
            }
            updateSizeInputs();
        }

        function applyViewBoxString(value, { persist = true, syncInputs = true } = {}) {
            const sanitized = sanitizeViewBoxValue(value);
            if (!sanitized) {
                return false;
            }
            const lengths = ensureParsedLengths(sanitized);
            if (!lengths) {
                return false;
            }
            body.style.setProperty('--item-image-view-box', sanitized);
            if (persist) {
                persistValue(sanitized);
            }
            if (syncInputs) {
                syncInputsFromParsedLengths(lengths);
            } else {
                updateSizeInputs();
            }
            return true;
        }

        const hasInputs = Boolean(topInput && leftInput && heightInput && widthInput);

        if (!applyViewBoxString(initialValue, { persist: false, syncInputs: hasInputs })) {
            initialValue = defaultValue;
            if (!applyViewBoxString(defaultValue, { persist: false, syncInputs: hasInputs })) {
                applyViewBoxString(VIEW_BOX_FALLBACK, { persist: false, syncInputs: hasInputs });
            }
            if (storedValue) {
                persistValue('');
            }
        }

        if (!hasInputs) {
            return;
        }

        function clearStatus() {
            [topInput, leftInput, heightInput, widthInput].forEach((input) => {
                if (input) {
                    input.setCustomValidity('');
                }
            });
        }

        function readNumericInput(input) {
            if (!input) {
                return Number.NaN;
            }
            const { value } = input;
            if (value == null || value === '') {
                return Number.NaN;
            }
            const parsed = Number.parseFloat(value);
            return Number.isFinite(parsed) ? parsed : Number.NaN;
        }

        function normalizeUnit(unit) {
            if (typeof unit === 'string' && unit.trim()) {
                return unit.trim();
            }
            return 'px';
        }

        function formatInsetString(lengthValues, unit) {
            const normalizedUnit = normalizeUnit(unit);
            const keys = ['top', 'right', 'bottom', 'left'];
            const parts = keys.map((key) => {
                const number = Number.isFinite(lengthValues[key]) ? Math.max(0, lengthValues[key]) : 0;
                const rounded = Math.round(number * 1000) / 1000;
                const text = Number.isInteger(rounded)
                    ? String(rounded)
                    : rounded.toFixed(3).replace(/0+$/, '').replace(/\.$/, '');
                return `${text}${normalizedUnit}`;
            });
            return `inset(${parts.join(' ')})`;
        }

        function setImageDimensions(width, height) {
            const w = Number(width);
            const h = Number(height);
            if (!Number.isFinite(w) || !Number.isFinite(h) || w <= 0 || h <= 0) {
                return;
            }
            const changed = !imageDimensions || imageDimensions.width !== w || imageDimensions.height !== h;
            imageDimensions = { width: w, height: h };
            if (changed || !widthInput.value || !heightInput.value) {
                updateSizeInputs();
            }
        }

        function resolveImageDimensions() {
            if (imageDimensions && imageDimensions.width > 0 && imageDimensions.height > 0) {
                return imageDimensions;
            }
            if (!dom.gallery) {
                return imageDimensions;
            }
            const candidate = dom.gallery.querySelector('img');
            if (candidate && candidate.naturalWidth && candidate.naturalHeight) {
                setImageDimensions(candidate.naturalWidth, candidate.naturalHeight);
            }
            return imageDimensions;
        }

        function handleImageLoad(event) {
            const target = event.target;
            if (!target || target.tagName !== 'IMG') {
                return;
            }
            if (dom.gallery && dom.gallery.contains(target)) {
                setImageDimensions(target.naturalWidth, target.naturalHeight);
            }
        }

        document.addEventListener('load', handleImageLoad, true);
        resolveImageDimensions();

        const inputs = [topInput, leftInput, heightInput, widthInput];
        inputs.forEach((input) => {
            if (!input) {
                return;
            }
            input.addEventListener('input', () => {
                input.setCustomValidity('');
            });
            input.addEventListener('keydown', (event) => {
                if (event.key === 'Enter') {
                    event.preventDefault();
                    handleApply();
                }
            });
        });

        function handleApply() {
            clearStatus();
            const dimensions = resolveImageDimensions();
            if (!dimensions) {
                console.warn('画像の読み込み完了後に設定してください。');
                return;
            }

            const topValue = readNumericInput(topInput);
            if (!Number.isFinite(topValue) || topValue < 0) {
                return reportInputError(topInput, '上方向の値には0以上の数値を入力してください。');
            }

            const leftValue = readNumericInput(leftInput);
            if (!Number.isFinite(leftValue) || leftValue < 0) {
                return reportInputError(leftInput, '左方向の値には0以上の数値を入力してください。');
            }

            const heightValue = readNumericInput(heightInput);
            if (!Number.isFinite(heightValue) || heightValue <= 0) {
                return reportInputError(heightInput, '縦幅には0より大きい数値を入力してください。');
            }

            const widthValue = readNumericInput(widthInput);
            if (!Number.isFinite(widthValue) || widthValue <= 0) {
                return reportInputError(widthInput, '横幅には0より大きい数値を入力してください。');
            }

            if (topValue + heightValue > dimensions.height + 1e-6) {
                return reportInputError(heightInput, '縦幅が画像サイズを超えています。');
            }

            if (leftValue + widthValue > dimensions.width + 1e-6) {
                return reportInputError(widthInput, '横幅が画像サイズを超えています。');
            }

            const rightValue = Math.max(dimensions.width - leftValue - widthValue, 0);
            const bottomValue = Math.max(dimensions.height - topValue - heightValue, 0);

            const unit = viewBoxUnit || 'px';
            const viewBoxString = formatInsetString(
                {
                    top: topValue,
                    right: rightValue,
                    bottom: bottomValue,
                    left: leftValue
                },
                unit
            );

            applyViewBoxString(viewBoxString);
        }

        function reportInputError(input, message) {
            if (input) {
                input.setCustomValidity(message);
                input.reportValidity();
            }
            console.warn(message);
        }

        if (applyButton) {
            applyButton.addEventListener('click', handleApply);
        }

        if (resetButton) {
            resetButton.addEventListener('click', () => {
                clearStatus();
                applyViewBoxString(defaultValue, { persist: true, syncInputs: true });
            });
        }
    }

    const duplicates = createDuplicateManager(() => state.csvPath);

    const storageManagerFactory = window.galleryStorageManagerFactory || null;
    if (!storageManagerFactory || typeof storageManagerFactory.createStorageManager !== 'function') {
        throw new Error('gallery storage manager factory is not available');
    }

    const storageManager = storageManagerFactory.createStorageManager({
        storageUtils,
        getRecords: () => state.records,
        getDatasetState: () => datasetState,
        getCsvPath: () => state.csvPath,
        resolveCsvSavePath,
        setStorageStatus
    });

    const renderFactory = window.galleryRenderFactory || null;

    const effectModule =
        renderFactory && typeof renderFactory.createEffectFactory === 'function'
            ? renderFactory.createEffectFactory({
                  state,
                  datasetState,
                  masterDatalistId: MASTER_DATALIST_ID,
                  demeritDatalistId: MASTER_DEMERIT_DATALIST_ID,
                  createElement,
                  sanitizeLevelList,
                  sortLevelsAscending,
                  applyMasterLevelOptions,
                  normalizeStatus,
                  statusLabel
              })
            : null;

    if (!effectModule) {
        throw new Error('gallery effect factory is not available');
    }

    const {
        createEffect,
        updateEffectStatus,
        rebuildLevelSelectOptions,
        setCorrectionLevelCandidates,
        getEffectIndexes,
        createCorrectionInput,
        updateInputValueAttribute,
        updateLevelInputAvailability,
        syncDemeritAvailability
    } = effectModule;


    function collectCsvHeaders(records) {
        const seen = new Set();
        const headers = [];
        const register = (key) => {
            if (!key || seen.has(key)) {
                return;
            }
            seen.add(key);
            headers.push(key);
        };

        records.forEach((record) => {
            if (!record || typeof record !== 'object') {
                return;
            }
            Object.keys(record).forEach(register);
        });

        return headers.length ? headers : ['Image'];
    }

    function csvEscape(value) {
        const text = value == null ? '' : String(value);
        if (!/[",\n]/.test(text)) {
            return text;
        }
        return '"' + text.replace(/"/g, '""') + '"';
    }

    function generateCsv(records) {
        if (!Array.isArray(records) || !records.length) {
            return '';
        }
        const headers = collectCsvHeaders(records);
        const lines = [headers.map(csvEscape).join(',')];

        records.forEach((record) => {
            const row = headers.map((key) => {
                if (!record || typeof record !== 'object') {
                    return csvEscape('');
                }
                let value = Object.prototype.hasOwnProperty.call(record, key) ? record[key] : '';
                if (key === 'Tags') {
                    value = serializeRecordTags(value);
                }
                return csvEscape(value);
            });
            lines.push(row.join(','));
        });

        return lines.join('\n');
    }

    function csvFileName() {
        const baseName = getFileName(state.csvPath) || 'results.csv';
        const converted = baseName.replace(/\.csv$/i, '_review.csv');
        if (converted !== baseName) {
            return converted;
        }
        if (!baseName) {
            return 'results_review.csv';
        }
        return `${baseName.replace(/\.csv$/i, '')}_review.csv`;
    }

    const storesNamespace = typeof window !== 'undefined' && window ? window.galleryStores : null;
    const createFilterStoreFn =
        storesNamespace && typeof storesNamespace.createFilterStore === 'function'
            ? storesNamespace.createFilterStore
            : null;
    const createTagStoreFn =
        storesNamespace && typeof storesNamespace.createTagStore === 'function'
            ? storesNamespace.createTagStore
            : null;

    const filterStore =
        typeof createFilterStoreFn === 'function'
            ? createFilterStoreFn({
                  searchTerm: dom.searchInput && typeof dom.searchInput.value === 'string' ? dom.searchInput.value : '',
                  statusFilter: dom.filterSelect && dom.filterSelect.value ? dom.filterSelect.value : 'all',
                  colorFilter: dom.colorFilter && dom.colorFilter.value ? dom.colorFilter.value : 'all',
                  includeDuplicates: Boolean(dom.showDuplicatesToggle && dom.showDuplicatesToggle.checked)
              })
            : null;

    const tagStore =
        typeof createTagStoreFn === 'function'
            ? createTagStoreFn({
                  parseTagTokens,
                  formatTagTokens,
                  getRecordByIndex,
                  setRecordTags
              })
            : null;

    const eventsFactory = window.galleryEventsFactory || null;
    const galleryEvents =
        eventsFactory && typeof eventsFactory.createGalleryEvents === 'function'
            ? eventsFactory.createGalleryEvents({
                  dom,
                  state,
                  datasetState,
                  duplicates,
                  showStatus,
                  clearStatus,
                  setStorageStatus,
                  parseCsvRecords,
                  loadRecordsArray,
                  generateCsv,
                  csvFileName,
                  sanitizeLevelList,
                  sortLevelsAscending,
                  updateEffectStatus,
                  setCorrectionLevelCandidates,
                  rebuildLevelSelectOptions,
                  createCorrectionInput,
                  getEffectIndexes,
                  updateInputValueAttribute,
                  updateLevelInputAvailability,
                  applyMasterLevelOptions,
                  validateMasterEffectValue,
                  validateMasterDemeritValue,
                  syncDemeritAvailability,
                  createTagInputEvents: eventsFactory ? eventsFactory.createTagInputEvents : null,
                  tagStore,
                  filterStore
              })
            : null;

    if (!galleryEvents) {
        throw new Error('gallery events factory is not available');
    }

    const { bindImage, attachEventHandlers } = galleryEvents;

    const galleryView =
        renderFactory && typeof renderFactory.createGalleryView === 'function'
            ? renderFactory.createGalleryView({
                  state,
                  datasetState,
                  stateApi,
                  dom,
                  duplicates,
                  itemColorOptions: ITEM_COLOR_OPTIONS,
                  relicTypeOptions: ITEM_RELIC_TYPE_OPTIONS,
                  createEffect,
                  bindImage,
                  createElement,
                  joinPath,
                  getFileName,
                  showStatus,
                  clearStatus,
                  ensureDomElement,
                  applyInlineStyles: applyInlineStylesToElement,
                  normalizeStatus,
                  getRecordByIndex,
                  isRecordDuplicate,
                  isRecordFavorite,
                  tagStore,
                  filterStore
              })
            : null;

    if (!galleryView) {
        throw new Error('gallery render factory is not available');
    }

    const {
        buildGallery,
        applyFilters,
        setOcrVisibility,
        getOcrToggleState,
        getItemContext,
        updateFavoriteVisuals,
        updateDuplicateVisuals,
        applyItemColor,
        normalizeItemColor,
        applyItemRelicType,
        normalizeItemRelicType,
        applyItemTags,
        normalizeItemTags,
        refreshItemCaches,
        syncTagSearchOptions: syncTagSearchOptionsFromView
    } = galleryView;

    syncTagSearchOptions = typeof syncTagSearchOptionsFromView === 'function' ? syncTagSearchOptionsFromView : null;

    attachEventHandlers({
        switchDataset,
        setRelicTypeFilter: setActiveRelicType,
        buildGallery,
        applyFilters,
        setOcrVisibility,
        getOcrToggleState,
        getItemContext,
        updateFavoriteVisuals,
        updateDuplicateVisuals,
        applyItemColor,
        normalizeItemColor,
        applyItemRelicType,
        normalizeItemRelicType,
        applyItemTags,
        normalizeItemTags,
        refreshItemCaches,
        tagStore,
        filterStore,
        getRecordByIndex,
        isRecordDuplicate,
        isRecordFavorite,
        setRecordDuplicate,
        setRecordFavorite,
        setRecordItemColor,
        setRecordItemRelicType,
        setRecordTags,
        applyMasterDataForRelicType,
        recordStatusChange,
        updateRecordEffectValue,
        updateRecordLevelValue,
        updateRecordLevelOptions,
        scheduleSave: () => storageManager.scheduleSave()
    });

    const appController = createAppController({
        attachEventHandlers,
        prepareInitialDataset,
        setupDatasetSelector,
        ensureMasterLevels,
        ensureMasterOptions,
        ensureMasterDemeritOptions,
        datasetState,
        switchDataset,
        loadInitialData
    });

    void appController.initialize();

    stateStore.subscribe(handleStateChange);
    handleStateChange();

    function setupDatasetSelector() {
        if (!dom.datasetSelector || !dom.datasetSelect) {
            return;
        }
        const currentIndex = clampDatasetIndex(datasetState.activeIndex);
        const currentDataset = datasetState.list && datasetState.list[currentIndex];
        const currentType = getDatasetRelicType(currentDataset);
        const availableTypes = getAvailableRelicTypes();
        if (
            currentType &&
            currentType !== RELIC_TYPE_MERGED &&
            activeRelicType !== RELIC_TYPE_ALL &&
            activeRelicType !== currentType &&
            availableTypes.has(currentType)
        ) {
            activeRelicType = currentType;
        }
        updateRelicTypeSelector();
        if (!Array.isArray(datasetState.list) || !datasetState.list.length) {
            clearElementChildren(dom.datasetSelect);
            setElementHidden(dom.datasetSelector, true);
            return;
        }
        rebuildDatasetOptions(currentIndex);
    }

    function updateDatasetIndicator() {
        if (!dom.datasetSelector || !dom.datasetSelect) {
            return;
        }
        const currentIndex = clampDatasetIndex(datasetState.activeIndex);
        const currentDataset = datasetState.list && datasetState.list[currentIndex];
        const currentType = getDatasetRelicType(currentDataset);
        const availableTypes = getAvailableRelicTypes();
        if (
            currentType &&
            currentType !== RELIC_TYPE_MERGED &&
            activeRelicType !== RELIC_TYPE_ALL &&
            activeRelicType !== currentType &&
            availableTypes.has(currentType)
        ) {
            activeRelicType = currentType;
        }
        updateRelicTypeSelector();
        if (!Array.isArray(datasetState.list) || !datasetState.list.length) {
            setElementHidden(dom.datasetSelector, true);
            return;
        }
        rebuildDatasetOptions(currentIndex);
    }

    function parseLabelSymbols(jsonText) {
        try {
            const parsed = JSON.parse(jsonText || '[]');
            if (Array.isArray(parsed) && parsed.length) {
                return parsed
                    .map((symbol) => (symbol == null ? '' : String(symbol)))
                    .filter((symbol) => symbol !== '')
                    .slice();
            }
        } catch (error) {
            console.warn('label symbolsの解析に失敗しました:', error);
        }
        return ['①', '②', '③'];
    }

    function applyDatasetState(descriptor) {
        stateStore.updateDescriptor(descriptor);
        const targetType = descriptor && typeof descriptor === 'object' ? descriptor.relicType : datasetState.relicType;
        applyMasterDataForType(targetType);
    }

    function updateSaveAvailability() {
        if (datasetState.kind === 'merged') {
            setStorageStatus('統合ビューは読み取り専用です。個別データセットを選択してください。', true);
        } else {
            setStorageStatus('変更は即座にCSVへ保存されます。', false);
        }
    }

    function datasetOptionLabel(dataset, index) {
        if (!dataset) {
            return `データセット ${index + 1}`;
        }
        const baseLabel = dataset.label || `データセット ${index + 1}`;
        const folder = dataset.folder || '';
        if (folder && folder !== baseLabel) {
            const suffix = `(${folder})`;
            if (!baseLabel.endsWith(suffix)) {
                return `${baseLabel} ${suffix}`;
            }
        }
        return baseLabel;
    }

    function showStatus(message, isError) {
        updateStatusElement(dom.galleryStatus, message, { isError, display: 'block' });
    }

    function clearStatus() {
        showStatus('', false);
    }

    function setStorageStatus(message, isError) {
        updateStatusElement(dom.storageStatus, message, { isError, display: 'inline' });
    }

    function createElement(tag, className, text) {
        const element = document.createElement(tag);
        if (className) {
            element.className = className;
        }
        if (text != null) {
            element.textContent = text;
        }
        return element;
    }







    function updateRecordEffectValue(recordIndex, slotIndex, value, kind = 'effect') {
        if (Number.isNaN(recordIndex) || Number.isNaN(slotIndex)) {
            return false;
        }
        const key = kind === 'demerit' ? `Demerit${slotIndex}` : `Effect${slotIndex}`;
        return updateRecordField(recordIndex, key, value);
    }

    function updateRecordLevelValue(recordIndex, slotIndex, value, kind = 'effect') {
        if (Number.isNaN(recordIndex) || Number.isNaN(slotIndex)) {
            return false;
        }
        if (kind === 'demerit') {
            return false;
        }
        const key = `Effect${slotIndex}Level`;
        return updateRecordField(recordIndex, key, value);
    }
    function updateRecordLevelOptions(recordIndex, slotIndex, value, kind = 'effect') {
        if (Number.isNaN(recordIndex) || Number.isNaN(slotIndex)) {
            return false;
        }
        if (kind === 'demerit') {
            return false;
        }
        const key = `Effect${slotIndex}LevelOptions`;
        return updateRecordField(recordIndex, key, value);
    }
    function recordStatusChange(effect, status) {
        const indexes = getEffectIndexes(effect);
        if (!indexes) {
            return false;
        }
        const record = getRecordByIndex(indexes.recordIndex);
        if (!record) {
            return false;
        }
        const key =
            indexes.kind === 'demerit'
                ? `Demerit${indexes.slotIndex}Status`
                : `Effect${indexes.slotIndex}Status`;
        if (record[key] !== status) {
            record[key] = status;
            storageManager.scheduleSave();
            return true;
        }
        return false;
    }


    function ensureLabelCoverage(records) {
        let maxSlot = state.labelSymbols.length;
        records.forEach((record) => {
            if (!record || typeof record !== 'object') {
                return;
            }
            Object.keys(record).forEach((key) => {
                const match = /^Effect(\d+)$/.exec(key);
                if (match) {
                    const slot = parseInt(match[1], 10);
                    if (!Number.isNaN(slot) && slot > maxSlot) {
                        maxSlot = slot;
                    }
                }
            });
        });
        stateApi.ensureLabelSymbolsLength(maxSlot, (slot) => `Slot ${slot}`);
    }

    function loadRecordsArray(data) {
        let records = Array.isArray(data) ? data.slice() : data && typeof data === 'object' ? [data] : [];
        const levelPlaceholdersApplied = normalizeEffectLevelPlaceholdersRecords(records);
        if (Array.isArray(levelPlaceholdersApplied)) {
            records = levelPlaceholdersApplied;
        }
        const relicNormalized = normalizeRelicTypeColumns(records);
        if (Array.isArray(relicNormalized)) {
            records = relicNormalized;
        }
        ensureLabelCoverage(records);
        stateApi.setRecords(records);
        duplicates.prepare();
        if (typeof syncTagSearchOptions === 'function') {
            syncTagSearchOptions(records, { clearSelection: true });
        }
        buildGallery();
    }

    async function loadInitialData() {
        const preferredName = getFileName(state.csvPath) || 'results.csv';

        try {
            const text = await storageManager.tryLoad(preferredName);
            if (text) {
                loadRecordsArray(JSON.parse(text));
                clearStatus();
                setStorageStatus('ブラウザから読み込みました。', false);
                return;
            }
        } catch (error) {
            console.warn('ブラウザからの読み込みに失敗しました:', error);
        }

        const isMerged =
            datasetState.kind === 'merged' &&
            Array.isArray(datasetState.sources) &&
            datasetState.sources.length > 0;
        if (isMerged) {
            try {
                showStatus('読み込み中...', false);
                const mergedRecords = await loadMergedRecords(datasetState.sources);
                loadRecordsArray(mergedRecords);
                clearStatus();
            } catch (error) {
                console.error('結合データセットのロードに失敗しました:', error);
                showStatus(`結合データセットの読み込みに失敗しました: ${error.message || error}`, true);
            }
            return;
        }

        if (!state.csvPath) {
            return;
        }

        try {
            showStatus('読み込み中...', false);
            const response = await fetch(state.csvPath, { cache: 'no-cache' });
            if (!response.ok) {
                throw new Error(`HTTP ${response.status}`);
            }
            const csvText = await response.text();
            const records = parseCsvRecords(csvText);
            loadRecordsArray(records);
            clearStatus();
        } catch (error) {
            console.error('CSVのロードに失敗しました:', error);
            showStatus(`データの読み込みに失敗しました: ${error.message || error}. CSV出力の配置を確認してください。`, true);
        }
    }


    function joinPath(base, leaf) {
        if (!leaf) {
            return base || '';
        }
        if (!base) {
            return leaf;
        }
        const cleanBase = base.replace(/[\/]+$/, '');
        const cleanLeaf = leaf.replace(/^[\/]+/, '');
        return `${cleanBase}/${cleanLeaf}`;
    }

    function getFileName(path) {
        if (!path) {
            return '';
        }
        const parts = path.split(/[\\/]/);
        return parts[parts.length - 1] || '';
    }






})();
