// Generated by RelicListMaker __APP_VERSION__
import { registerModuleEntryManifest, resolveModuleLoadGroups } from './js/modules/moduleEntries.js';
import { DEFAULT_BOOTSTRAP_SCHEMA, validateBootstrapConfig } from './js/modules/bootstrapConfig.js';

registerModuleEntryManifest();

const MODULE_LOAD_GROUPS = resolveModuleLoadGroups({ includeLegacyCompat: true });

const DEFAULT_BOOTSTRAP_JSON = './gallery_data.json';

function resolveModuleUrl(specifier, baseUrl) {
    try {
        return new URL(specifier, baseUrl).href;
    } catch (error) {
        console.error('モジュールの解決に失敗しました:', specifier, error);
        return null;
    }
}

function resolveBootstrapJsonUrl(rawSpecifier) {
    const candidate = typeof rawSpecifier === 'string' ? rawSpecifier.trim() : '';
    if (!candidate) {
        return resolveModuleUrl(DEFAULT_BOOTSTRAP_JSON, document.baseURI || import.meta.url);
    }
    return resolveModuleUrl(candidate, document.baseURI || import.meta.url);
}

function createDependencyLoadTracer() {
    const records = [];
    const now = () => (typeof performance !== 'undefined' && performance.now ? performance.now() : Date.now());

    return {
        start(group) {
            const startedAt = now();
            return {
                finish(results) {
                    const durationMs = now() - startedAt;
                    const failures = results.filter((result) => result.status === 'rejected').length;
                    records.push({
                        id: group.id,
                        mode: group.mode,
                        durationMs,
                        failures,
                        count: group.entries.length
                    });
                }
            };
        },
        report() {
            records.forEach((record) => {
                const message = `依存グループ[${record.id}] (${record.mode}) ${record.durationMs.toFixed(1)}ms`;
                if (record.failures > 0) {
                    console.warn(`${message} / 失敗: ${record.failures}`);
                } else {
                    console.info(message);
                }
            });
        }
    };
}

async function loadDependencyEntry(entry, baseUrl) {
    const resolved = resolveModuleUrl(entry.specifier, baseUrl);
    if (!resolved) {
        throw new Error(`モジュールのURLが解決できませんでした: ${entry.specifier}`);
    }
    await import(resolved);
}

async function loadDependencyGroup(group, baseUrl) {
    const importEntry = (entry) =>
        loadDependencyEntry(entry, baseUrl).then(
            () => ({ status: 'fulfilled', entry }),
            (error) => ({ status: 'rejected', entry, reason: error })
        );

    if (group.mode === 'parallel') {
        return Promise.all(group.entries.map((entry) => importEntry(entry)));
    }

    const results = [];
    for (const entry of group.entries) {
        // 逐次ロードで失敗したら後続をスキップする
        // (依存順序があるモジュール間での暗黙依存を守るため)
        const result = await importEntry(entry);
        results.push(result);
        if (result.status === 'rejected') {
            break;
        }
    }
    return results;
}

async function loadDependencies() {
    const baseUrl = import.meta.url;
    const tracer = createDependencyLoadTracer();

    for (const group of MODULE_LOAD_GROUPS) {
        const tracker = tracer.start(group);
        const results = await loadDependencyGroup(group, baseUrl);
        tracker.finish(results);

        const failed = results.filter((result) => result.status === 'rejected');
        if (failed.length) {
            tracer.report();
            const errorDetails = failed
                .map((result) => `${result.entry.id || result.entry.specifier}: ${result.reason}`)
                .join('; ');
            throw new Error(`依存グループ「${group.id}」の読み込みに失敗しました: ${errorDetails}`);
        }
    }

    tracer.report();
}

function applyGeneratorMeta(appVersion) {
    if (!appVersion) {
        return;
    }
    const meta = document.querySelector('meta[name="generator"]');
    if (!meta) {
        return;
    }
    meta.setAttribute('content', `RelicListMaker ${appVersion}`);
}

function toDatasetString(value, fallback = '') {
    if (value == null) {
        return fallback;
    }
    if (typeof value === 'string') {
        return value;
    }
    return String(value);
}

function toJsonText(value, fallback = '') {
    if (value == null) {
        return fallback;
    }
    if (typeof value === 'string') {
        return value;
    }
    try {
        return JSON.stringify(value);
    } catch (error) {
        console.error('JSON文字列への変換に失敗しました:', error);
    }
    return fallback;
}

function hasBootstrapValue(value) {
    if (value === undefined || value === null) {
        return false;
    }
    if (typeof value === 'string') {
        return value.trim().length > 0;
    }
    return true;
}

const DATASET_MAPPINGS = [
    { key: 'resultsCsv', datasetKey: 'resultsCsv', defaultValue: '', formatter: toDatasetString },
    { key: 'imgDir', datasetKey: 'imgDir', defaultValue: '.', formatter: toDatasetString },
    { key: 'labelSymbols', datasetKey: 'labelSymbols', defaultValue: [], formatter: toJsonText },
    { key: 'masterCsv', datasetKey: 'masterCsv', defaultValue: '', formatter: toDatasetString },
    { key: 'masterJson', datasetKey: 'masterJson', defaultValue: '', formatter: toDatasetString },
    { key: 'masterOptions', datasetKey: 'masterOptions', defaultValue: [], formatter: toJsonText },
    { key: 'masterOptionsMap', datasetKey: 'masterOptionsMap', defaultValue: {}, formatter: toJsonText },
    { key: 'masterLevels', datasetKey: 'masterLevels', defaultValue: {}, formatter: toJsonText },
    { key: 'masterLevelsMap', datasetKey: 'masterLevelsMap', defaultValue: {}, formatter: toJsonText },
    { key: 'masterCsvMap', datasetKey: 'masterCsvMap', defaultValue: {}, formatter: toJsonText },
    { key: 'masterDemeritCsv', datasetKey: 'masterDemeritCsv', defaultValue: '', formatter: toDatasetString },
    {
        key: 'masterDemeritJson',
        datasetKey: 'masterDemeritJson',
        defaultValue: '',
        formatter: toDatasetString
    },
    { key: 'masterDemeritOptions', datasetKey: 'masterDemeritOptions', defaultValue: [], formatter: toJsonText },
    { key: 'masterDemeritOptionsMap', datasetKey: 'masterDemeritOptionsMap', defaultValue: {}, formatter: toJsonText },
    { key: 'masterDemeritCsvMap', datasetKey: 'masterDemeritCsvMap', defaultValue: {}, formatter: toJsonText },
    { key: 'masterDemeritRulesMap', datasetKey: 'masterDemeritRulesMap', defaultValue: {}, formatter: toJsonText },
    { key: 'datasets', datasetKey: 'datasets', defaultValue: [], formatter: toJsonText },
    { key: 'activeDataset', datasetKey: 'activeDataset', defaultValue: '', formatter: toDatasetString },
    {
        key: 'itemImageViewBox',
        datasetKey: 'defaultItemImageViewBox',
        defaultValue: '',
        formatter: toDatasetString,
        styleProperty: '--item-image-view-box'
    },
    {
        key: 'appVersion',
        datasetKey: 'appVersion',
        defaultValue: '',
        formatter: toDatasetString,
        afterApply: (value) => applyGeneratorMeta(value)
    },
    { key: 'coreScript', datasetKey: 'coreScript', defaultValue: '', formatter: toDatasetString }
];

function applyBootstrapData(bootstrapData = {}) {
    const body = document.body;
    if (!body || !body.dataset) {
        return;
    }

    const dataset = body.dataset;

    DATASET_MAPPINGS.forEach((mapping) => {
        const { key, datasetKey, defaultValue, formatter, afterApply, styleProperty } = mapping;
        const rawValue = Object.prototype.hasOwnProperty.call(bootstrapData, key)
            ? bootstrapData[key]
            : undefined;
        const datasetValue = dataset[datasetKey];
        const resolvedValue = hasBootstrapValue(rawValue)
            ? rawValue
            : hasBootstrapValue(datasetValue)
              ? datasetValue
              : defaultValue;

        const fallbackText = formatter(defaultValue, '');
        dataset[datasetKey] = formatter(resolvedValue, fallbackText);

        const styleValue = hasBootstrapValue(resolvedValue) ? resolvedValue : '';
        if (styleProperty && styleValue) {
            body.style.setProperty(styleProperty, styleValue);
        }
        if (typeof afterApply === 'function') {
            afterApply(styleValue || resolvedValue);
        }
    });
}

async function loadBootstrapData() {
    const body = document.body;
    const bootstrapSpec = body && body.dataset ? body.dataset.bootstrapJson : '';
    const resolvedUrl = resolveBootstrapJsonUrl(bootstrapSpec);
    if (!resolvedUrl) {
        console.error('ブートストラップJSONのURLが解決できませんでした。');
        return {};
    }

    try {
        const response = await fetch(resolvedUrl, { cache: 'no-cache' });
        if (!response.ok) {
            console.error('ブートストラップJSONの読み込みに失敗しました:', response.status);
            return {};
        }
        return await response.json();
    } catch (error) {
        console.error('ブートストラップJSONの取得に失敗しました:', error);
        return {};
    }
}

function resolveCoreScriptUrl(rawSpecifier) {
    if (!rawSpecifier) {
        return resolveModuleUrl('./gallery.js', import.meta.url);
    }
    const trimmed = rawSpecifier.trim();
    if (!trimmed) {
        return resolveModuleUrl('./gallery.js', import.meta.url);
    }
    try {
        return new URL(trimmed, document.baseURI).href;
    } catch (error) {
        console.error('コアスクリプトの解決に失敗しました:', rawSpecifier, error);
        return resolveModuleUrl(trimmed, import.meta.url);
    }
}

async function bootstrapGallery() {
    try {
        const rawBootstrapData = await loadBootstrapData();
        const { config: bootstrapConfig, warnings } = validateBootstrapConfig(
            DEFAULT_BOOTSTRAP_SCHEMA,
            rawBootstrapData
        );
        warnings.forEach((message) => console.warn(message));

        applyBootstrapData(bootstrapConfig);
        await loadDependencies();
        const body = document.body;
        const coreScriptSource =
            (body && body.dataset ? body.dataset.coreScript : '') || bootstrapConfig.coreScript;
        const coreScriptUrl = resolveCoreScriptUrl(coreScriptSource);
        if (!coreScriptUrl) {
            console.error('コアスクリプトのURLが解決できませんでした。');
            return;
        }
        await import(coreScriptUrl);
    } catch (error) {
        console.error('ギャラリー初期化中にエラーが発生しました:', error);
    }
}

function startWhenReady() {
    if (document.readyState === 'loading') {
        document.addEventListener(
            'DOMContentLoaded',
            () => {
                void bootstrapGallery();
            },
            { once: true }
        );
        return;
    }
    void bootstrapGallery();
}

startWhenReady();
